// ── TAHOE OFF-ROAD TRI · TRAINING PLAN ───────────────────────────────────────
// Edit this file to update the schedule.
// Structure: phases → weeks → days (Mon–Sun) → slots → workouts
//
// Races:
//   Broken Arrow 23K  ·  Jun 21, 2026  ·  14.25 mi, 4,500 ft
//   Tahoe Off-Road Tri  ·  Jul 11, 2026  ·  Swim + MTB + Run

const PLAN = [
 {phase:1,phaseTitle:"Base Building",phaseDesc:"Establish the 6-day routine, introduce MTB, build aerobic base",phaseWeeks:"Weeks 1–4 · Mar 30 – Apr 26",weeks:[
  {id:"w1",num:1,title:"Mar 30 – Apr 5 · Getting Rolling",badge:"build",start:"2026-03-30",
   notes:"<strong>The Sat/Sun weekend pattern is key.</strong> Long MTB Saturday followed by long run Sunday builds back-to-back aerobic endurance. Keep both easy in Phase 1.",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w1-1",type:"swim",label:"Swim",name:"Pool: 2,000m easy aerobic",detail:"Stroke efficiency and breathing rhythm. All easy.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w1-2",type:"strength",label:"Strength",name:"45 min",detail:"Single-leg squat, hip hinge, lateral band work, plank series, rotator cuff",anchor:true}]},{qual:"Aft",workouts:[{id:"w1-3",type:"bike",label:"MTB",name:"1.5 hr easy trail ride",detail:"Local singletrack — comfort over pace. Cornering basics, body position."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w1-4",type:"run",label:"Trail Run",name:"45 min easy",detail:"Easy aerobic. Practice uneven terrain. Don't push."}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w1-5",type:"run",label:"Trail Run",name:"5 miles easy",detail:"Hilly singletrack. Easy effort.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w1-6",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w1-7",type:"bike",label:"Long Ride",name:"2 hr easy MTB",detail:"Explore local singletrack. Easy pace — the long run follows tomorrow, so keep HR low.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w1-8",type:"run",label:"Long Run",name:"8 miles easy trail",detail:"Time on feet. Easy pace. 400–500 ft gain. Power hike steep sections.",anchor:true}]}]},
   ]},
  {id:"w2",num:2,title:"Apr 6 – Apr 12 · Adding Load",badge:"build",start:"2026-04-06",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w2-1",type:"swim",label:"Swim",name:"Pool: 2,400m — 4×200m at tempo",detail:"Warm up 400m, main set 4×200m at moderate-hard, 30 sec rest, cool-down",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w2-2",type:"strength",label:"Strength",name:"45 min — add load",detail:"Bulgarian split squat, deadlift, step-ups, dead bug series",anchor:true}]},{qual:"Aft",workouts:[{id:"w2-3",type:"bike",label:"MTB",name:"2 hr — skills focus",detail:"Cornering, braking, slow-speed drills. Look ahead, not at the wheel."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w2-4",type:"run",label:"Trail Run",name:"55 min with 4×20 sec strides",detail:"Easy run, add 4 pickups at the end to keep legs feeling sharp"}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w2-5",type:"run",label:"Trail Run",name:"5 miles — 2 miles at tempo",detail:"Warm 1.5 mi, 2 mi comfortably hard on trail, 1.5 mi easy cool-down",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w2-6",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w2-7",type:"bike",label:"Long Ride",name:"2.5 hr MTB",detail:"Moderate effort. Start to build climbing habit — Tahoe ORT is 22 miles of MTB with real vert.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w2-8",type:"run",label:"Long Run",name:"10 miles — 700+ ft gain",detail:"Mt. Tam or equivalent. Power hike steep bits. Easy overall effort.",anchor:true}]}]},
   ]},
  {id:"w3",num:3,title:"Apr 13 – Apr 19 · Volume Push",badge:"build",start:"2026-04-13",
   notes:"<strong>Poles:</strong> Broken Arrow 23K strongly encourages running poles. Start practicing on Sunday long runs now — they save serious energy on steep terrain.",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w3-1",type:"swim",label:"Swim",name:"Pool: 2,800m — 5×300m moderate",detail:"Main set: 5×300m at 80% effort, 45 sec rest",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w3-2",type:"strength",label:"Strength",name:"50 min — MTB-specific emphasis",detail:"Hip flexor mobility, lateral stability, rotator cuff, single-leg RDL",anchor:true}]},{qual:"Aft",workouts:[{id:"w3-3",type:"bike",label:"MTB",name:"2.5 hr — climbing focus",detail:"Seek climbs. Seated vs. standing technique. Pace the ascents."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w3-4",type:"run",label:"Trail Run",name:"65 min hilly — 500+ ft gain",detail:"Include 10×100m hill sprints mid-run for Broken Arrow climbing power"}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w3-5",type:"run",label:"Trail Run",name:"5 miles with hill repeats",detail:"Find a steep 100–200m hill. 8 repeats: sprint up, walk/jog down. Builds BA headwall power.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w3-6",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w3-7",type:"bike",label:"Long Ride",name:"3 hr MTB — endurance",detail:"Build toward race-distance riding. Eat on the bike — 300 cal/hr minimum.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w3-8",type:"run",label:"Long Run",name:"12 miles — big mountain day",detail:"Mt. Tam. 1,000+ ft gain. Mix of running and power hiking. Bring poles.",anchor:true}]}]},
   ]},
  {id:"w4",num:4,title:"Apr 20 – Apr 26 · Recovery Week",badge:"recovery",start:"2026-04-20",
   notes:"<strong>Recovery weeks are non-negotiable.</strong> This is when Phase 1 fitness is absorbed. The urge to push through is the exact reason to pull back.",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w4-1",type:"swim",label:"Swim",name:"Pool: 2,000m easy — technique only",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w4-2",type:"rest",label:"Rest",name:"Skip strength this week",rest:true}]},{qual:"Aft",workouts:[{id:"w4-3",type:"bike",label:"MTB",name:"1.5 hr easy — fun trails, no efforts"}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w4-4",type:"run",label:"Trail Run",name:"40 min very easy — flat or gentle trail"}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w4-5",type:"run",label:"Trail Run",name:"5 miles easy",detail:"Enjoy it. No intensity this week.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w4-6",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w4-7",type:"bike",label:"Long Ride",name:"2 hr easy MTB",detail:"Mellow. Keep the pattern but back off the effort.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w4-8",type:"run",label:"Long Run",name:"8 miles easy — volume drops 30%",anchor:true}]}]},
   ]},
 ]},
 {phase:2,phaseTitle:"Trail & MTB Build",phaseDesc:"Peak trail running volume for Broken Arrow; MTB intensity ramps in parallel",phaseWeeks:"Weeks 5–8 · Apr 27 – May 24",weeks:[
  {id:"w5",num:5,title:"Apr 27 – May 3 · Intensity Arrives",badge:"build",start:"2026-04-27",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w5-1",type:"swim",label:"Swim",name:"Pool: 2,800m — OWS simulation",detail:"Sight every 10 strokes, no lane-line dependency. 3×500m at moderate-hard.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w5-2",type:"strength",label:"Strength",name:"45 min — posterior chain",detail:"RDLs, glute bridges, Nordic hamstring curls, lateral band walks",anchor:true}]},{qual:"Aft",workouts:[{id:"w5-3",type:"bike",label:"MTB",name:"2.5 hr — 5×4 min climb intervals",detail:"Hard up, recover on the descent. Builds climbing fitness for Tahoe ORT."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w5-4",type:"run",label:"Trail Run",name:"70 min — 3×8 min tempo",detail:"20 min warm-up, 3 tempo efforts with 2 min jog recovery, cool-down"}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w5-5",type:"run",label:"Trail Run",name:"5 miles — fast finish",detail:"Easy first 3 miles, last 2 miles at Broken Arrow race effort.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w5-6",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w5-7",type:"bike",label:"Long Ride",name:"3 hr MTB — technical focus",detail:"Seek out rooty/rocky singletrack. Slow is smooth, smooth is fast.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w5-8",type:"run",label:"Long Run",name:"13 miles — mountain route with poles",detail:"Mt. Tam or equivalent. 1,200+ ft gain. Use poles on steep sections.",anchor:true}]}]},
   ]},
  {id:"w6",num:6,title:"May 4 – May 10 · Mountain Volume",badge:"build",start:"2026-05-04",
   notes:"<strong>Plan adjusted from actual Week 5 output (8.5 mi long run).</strong> Original plan called for 14–15 miles this week — too big a jump. Building to 10 miles keeps a safe progression toward a 12-mile peak in Week 9.",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w6-1",type:"swim",label:"Swim",name:"Pool: 3,000m — negative split 1500",detail:"Swim 1500m: first 750 controlled, second 750 progressively faster.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w6-2",type:"strength",label:"Strength",name:"45 min — core-heavy",detail:"Pallof press, Copenhagen plank, single-leg deadlift",anchor:true}]},{qual:"Aft",workouts:[{id:"w6-3",type:"bike",label:"MTB",name:"2.5 hr — descending focus",detail:"Weight back, look ahead, trust the tires. Lap the same descent."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w6-4",type:"run",label:"Trail Run",name:"70 min — 3×8 min tempo",detail:"Find runnable trail grade for efforts. Power hike in between."}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w6-5",type:"run",label:"Trail Run",name:"5 miles — sustained climbing",detail:"Find a trail with 600+ ft in 5 miles. Simulate BA climbing. Poles optional.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w6-6",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w6-7",type:"bike",label:"Long Ride",name:"2.5 hr MTB — climbing emphasis",detail:"Seek climbs. Back-to-back fatigue with tomorrow's run is intentional.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w6-8",type:"run",label:"Long Run",name:"10 miles — 700+ ft gain",detail:"Mt. Tam or equivalent. Controlled effort with poles on steep sections. Build from 8.5 last week.",anchor:true}]}]},
   ]},
  {id:"w7",num:7,title:"May 11 – May 17 · Sharpen + Open Water",badge:"build",start:"2026-05-11",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w7-1",type:"swim",label:"Swim",name:"Pool: 3,000m — 1500m time trial",detail:"Full effort on the 1500m. Log your time.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w7-2",type:"strength",label:"Strength",name:"40 min — reduce load this week",detail:"Maintenance only. Don't bury the legs before the big weekend.",anchor:true}]},{qual:"Aft",workouts:[{id:"w7-3",type:"bike",label:"MTB",name:"2.5 hr — 20+ miles singletrack",detail:"Race-distance simulation. Manage effort. Eat and drink on the bike."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w7-4",type:"ows",label:"Open Water",name:"OWS: 1,500–2,000m — first open water session",detail:"Practice starts, sighting, wetsuit comfort. Cold water prep begins here."}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w7-5",type:"run",label:"Trail Run",name:"5 miles at race effort",detail:"Treat this like a 5-mile race. Hard effort throughout.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w7-6",type:"rest",label:"Rest",name:"Full rest — big back-to-back coming",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w7-7",type:"bike",label:"Long Ride",name:"3–3.5 hr MTB — hardest technical ride",detail:"Hardest, most technical trails you can find. Build MTB confidence.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w7-8",type:"run",label:"Long Run",name:"11 miles — race-pace effort",detail:"Step up from 10 last week, push intensity. Race pace on runnable sections. Poles on all steep bits.",anchor:true}]}]},
   ]},
  {id:"w8",num:8,title:"May 18 – May 24 · Recovery Week",badge:"recovery",start:"2026-05-18",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w8-1",type:"swim",label:"Swim",name:"Pool: 2,200m easy + 8×50m fast",detail:"Mostly aerobic; short fast reps keep the snap",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w8-2",type:"rest",label:"Rest",name:"Skip strength — absorb Phase 2",rest:true}]},{qual:"Aft",workouts:[{id:"w8-3",type:"bike",label:"MTB",name:"1.5 hr easy — fun flow trails"}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w8-4",type:"run",label:"Trail Run",name:"45 min easy — conversational pace"}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w8-5",type:"run",label:"Trail Run",name:"5 miles easy with 4 strides at end",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w8-6",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w8-7",type:"bike",label:"Long Ride",name:"2 hr easy MTB",detail:"Keep the pattern. Easy effort.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w8-8",type:"run",label:"Long Run",name:"8.5 miles easy — back off volume",anchor:true}]}]},
   ]},
 ]},
 {phase:3,phaseTitle:"Broken Arrow Taper + Race",phaseDesc:"Peak in Wk 9, sharpen Wk 10, race sim Jun 13, single taper week, race Jun 21",phaseWeeks:"Weeks 9–12 · May 25 – Jun 21",weeks:[
  {id:"w9",num:9,title:"May 25 – May 31 · Peak Run Week",badge:"build",start:"2026-05-25",
   notes:"<strong>This is your peak long run week — 12 miles.</strong> That's 84% of BA race distance with a full week of recovery before you sharpen. Keep intensity high on climbs. Poles on the long run.",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w9-1",type:"swim",label:"Swim",name:"Pool: 2,600m — race pace sets",detail:"Main set: 3×400m at 1500m race pace, 90 sec rest. Feel fast.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w9-2",type:"strength",label:"Strength",name:"35 min — last heavy week",detail:"Full session. This is the last time you load before BA.",anchor:true}]},{qual:"Aft",workouts:[{id:"w9-3",type:"bike",label:"MTB",name:"2 hr with 4×5 min hard climbs",detail:"Hard efforts on climbs, recover on descents. Keep the engine running."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w9-4",type:"run",label:"Trail Run",name:"60 min with 3×8 min tempo",detail:"Warm up 15 min, 3 tempo efforts on trail, cool down. Race-specific intensity."}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w9-5",type:"run",label:"Trail Run",name:"5 miles at race effort with poles",detail:"Simulate BA race pace on climbs. Poles throughout.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w9-6",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w9-7",type:"bike",label:"Long Ride",name:"2.5 hr MTB — technical focus",detail:"Good effort. Last real long ride before BA taper begins.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w9-8",type:"run",label:"Long Run",name:"12 miles with poles — peak run",detail:"Mt. Tam. 1,000–1,200 ft gain. Sustained effort on climbs. This is your longest run before race day.",anchor:true}]}]},
   ]},
  {id:"w10",num:10,title:"Jun 1 – Jun 7 · Final Run Build",badge:"build",start:"2026-06-01",
   notes:"<strong>Keep building — no taper yet.</strong> Mini tri sim is Saturday June 13, BA is June 21. You have room for one more solid long run this Sunday before you ease off for the sim week. Peak long run is here.",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w10-1",type:"swim",label:"Swim",name:"Pool: 2,400m — 4×400m at race pace",detail:"Build race-pace endurance in the water. 90 sec rest between sets.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w10-2",type:"strength",label:"Strength",name:"20 min — activation only",detail:"Glute activation, hip mobility. Light load. Last strength session before race sim week.",anchor:true}]},{qual:"Aft",workouts:[{id:"w10-3",type:"bike",label:"MTB",name:"2 hr — 3×5 min hard climbs",detail:"Quality over duration. Hard up, recover on descents."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w10-4",type:"run",label:"Trail Run",name:"55 min moderate — hilly",detail:"Moderate effort. Seek vert. Poles optional."}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w10-5",type:"run",label:"Trail Run",name:"5 miles at race effort with poles",detail:"Last quality climbing run before sim week. Simulate BA pace on sustained hills.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w10-6",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w10-7",type:"bike",label:"Long Ride",name:"2.5 hr MTB — technical focus",detail:"Solid ride, moderate effort. Mini tri sim is next Saturday so make this count.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w10-8",type:"run",label:"Long Run",name:"13 miles with poles — peak long run",detail:"Mt. Tam. 1,000+ ft gain. This is your longest run before BA. Steady effort, controlled on descents.",anchor:true}]}]},
   ]},
  {id:"w11",num:11,title:"Jun 8 – Jun 14 · Mini Tri Simulation",badge:"peak",start:"2026-06-08",
   notes:"<strong>Saturday June 13 is your mini triathlon simulation.</strong> Keep Mon–Fri easy — protect the legs for a hard Saturday brick. This is your first full swim-bike-run rehearsal 4 weeks before Tahoe ORT. Taper for BA starts Sunday.",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w11-1",type:"swim",label:"Swim",name:"Pool: 1,800m easy — stay loose",detail:"Easy aerobic. No intensity. Legs are coming off a 13-mile peak run.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"",workouts:[{id:"w11-2",type:"run",label:"Easy Run",name:"25 min easy jog + 4 strides",detail:"Very light. Just keep blood moving. HR stays low all week until Saturday."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w11-3",type:"bike",label:"MTB",name:"45 min easy spin — gravel or road ok",detail:"Keep it very easy. Don't risk a crash on technical terrain this week."}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w11-4",type:"run",label:"Easy Run",name:"20 min easy + 4 strides",detail:"Shorter than Tuesday. Legs should feel springy by now.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w11-5",type:"rest",label:"Rest",name:"Full rest — mini tri tomorrow",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w11-6",type:"brick",label:"Mini Tri Sim",name:"Swim 1,000m → MTB 12mi → Run 2.5mi",detail:"Your first full triathlon rehearsal. Wetsuit on for the swim. Race vest and nutrition on the bike. Run off the bike at trail pace — practice the jelly legs. Use all race gear.",anchor:true,raceCard:"race-card"}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w11-7",type:"rest",label:"Rest",name:"Full rest — BA taper begins",rest:true}]}]},
   ]},
  {id:"w12",num:12,title:"Jun 15 – Jun 21 · Taper + Broken Arrow",badge:"broken",start:"2026-06-15",raceClass:"race-broken",
   notes:"<strong>This is your one taper week.</strong> You ran hard Saturday June 13 — let that fitness absorb. Volume drops to almost nothing. The race sim told you what you needed to know. Trust it.",
   raceBanner:{title:"Broken Arrow 23K — Jun 21, Palisades Tahoe",body:"<strong>14.25 miles, 4,500 ft gain, peaks at ~9,000 ft.</strong> Running poles are highly encouraged — learn to stow them quickly for the Stairway to Heaven ladder. Arrive Thu/Fri to acclimatize. Go out conservative on the first climb."},
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w12-1",type:"swim",label:"Swim",name:"Pool: 1,500m very easy",detail:"Drills and feel. Nothing hard this week.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"",workouts:[{id:"w12-2",type:"run",label:"Shakeout",name:"25 min easy jog + 4 strides",detail:"Loose and light. Just moving."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w12-3",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Thu",slots:[{qual:"",workouts:[{id:"w12-4",type:"travel",label:"Travel",name:"Drive to Palisades Tahoe",detail:"2–3 days early for altitude acclimatization. 6,200 ft base, race peaks at ~9,000 ft. Hydrate aggressively.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w12-5",type:"run",label:"Shakeout",name:"20 min easy jog + pole practice",detail:"Feel the altitude. Practice poles on the Village trails."}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w12-6",type:"rest",label:"Rest",name:"Race prep — full rest",detail:"Gear: poles, vest, 16oz+ water, 400+ cal gels, layers for 9,000 ft, ID.",rest:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w12-7",type:"race",label:"Race",name:"⛰ BROKEN ARROW 23K — 14.25 mi, 4,500 ft",detail:"Conservative first climb. Poles on every steep section. Stairway to Heaven: one free hand needed. Shirley Canyon will have snow. Finish at KT Sun Deck.",raceCard:"race-card-broken"}]}]},
   ]},
 ]},
 {phase:4,phaseTitle:"Tri-Specific Peak + Taper",phaseDesc:"Post-BA recovery, pivot to bricks and swim, peak then taper to Tahoe ORT",phaseWeeks:"Weeks 13–15 · Jun 22 – Jul 11",weeks:[
  {id:"w13",num:13,title:"Jun 22 – Jun 28 · Post-BA Recovery + Tri Pivot",badge:"recovery",start:"2026-06-22",
   notes:"<strong>Big shift this week:</strong> Saturday is now brick day. Your trail running fitness transfers directly to the Tahoe ORT run leg — you don't need more volume, just race-specific pattern training.",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w13-1",type:"swim",label:"Swim",name:"Pool: 2,200m easy — flush recovery",detail:"Easy aerobic only. Body is absorbing a hard race. Let it.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w13-2",type:"rest",label:"Rest",name:"Skip strength — legs recovering from BA",rest:true}]},{qual:"Aft",workouts:[{id:"w13-3",type:"bike",label:"MTB",name:"1.5 hr easy — mellow trails",detail:"Reintroduce the bike. No efforts. Fun ride."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w13-4",type:"run",label:"Trail Run",name:"40 min easy — legs check-in",detail:"Be honest about how you feel post-BA. Walk if needed."}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w13-5",type:"run",label:"Trail Run",name:"5 miles moderate",detail:"Your trail fitness carries directly to the Tahoe ORT run leg.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w13-6",type:"rest",label:"Rest",name:"Full rest",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w13-7",type:"brick",label:"Brick",name:"2 hr MTB → 25 min trail run",detail:"First brick. Easy effort on both legs.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w13-8",type:"run",label:"Easy Run",name:"40 min easy trail",detail:"Sunday transitions to shorter recovery run in the tri phase.",anchor:true}]}]},
   ]},
  {id:"w14",num:14,title:"Jun 29 – Jul 5 · Tri-Specific Peak",badge:"peak",start:"2026-06-29",
   notes:"<strong>Saturday's full race simulation is the most important session between now and race day.</strong> Use your wetsuit, race nutrition, race shoes, race everything.",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w14-1",type:"swim",label:"Swim",name:"Pool: 2,800m — race pace sets",detail:"3×500m at 1500m race pace, 90 sec rest. Log your splits.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"Morn",workouts:[{id:"w14-2",type:"strength",label:"Strength",name:"30 min activation — maintenance",detail:"Glute activation, hip mobility, core. Light load. No DOMS.",anchor:true}]},{qual:"Aft",workouts:[{id:"w14-3",type:"bike",label:"MTB",name:"2.5 hr — 3×15 min at race pace",detail:"Simulate Tahoe ORT bike intensity. Zone 3 on climbs, tech descent practice."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w14-4",type:"ows",label:"Open Water",name:"OWS: 1,500–2,000m",detail:"Wetsuit on. Cold water practice. Sighting, starts, mass-start simulation."}]}]},
    {day:"Thu",slots:[{qual:"Eve",workouts:[{id:"w14-5",type:"run",label:"Trail Run",name:"5 miles — 2×1 mile at race effort",detail:"Simulate running off the bike. Quick turnover, controlled effort.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w14-6",type:"rest",label:"Rest",name:"Full rest — big simulation Saturday",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w14-7",type:"brick",label:"Race Sim",name:"Swim 1500m → MTB 22mi → Run 5mi",detail:"Full race simulation! Use all race gear. Test nutrition end-to-end.",anchor:true}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w14-8",type:"run",label:"Easy Run",name:"30 min easy — active recovery",detail:"Shake out the legs after the big sim.",anchor:true}]}]},
   ]},
  {id:"w15",num:15,title:"Jul 6 – Jul 11 · Taper + Race",badge:"taper",start:"2026-07-06",raceClass:"race-tahoe",
   notes:"<strong>Taper anxiety is real.</strong> You'll feel sluggish, doubt your fitness, want to train more. Don't. Fitness is banked. The legs that feel weird now will feel electric on race morning.",
   days:[
    {day:"Mon",slots:[{qual:"Eve",workouts:[{id:"w15-1",type:"swim",label:"Swim",name:"Pool: 1,800m sharp — 10×100m at race pace",detail:"Feel fast. End confident.",anchor:true}]}]},
    {day:"Tue",slots:[{qual:"",workouts:[{id:"w15-2",type:"bike",label:"MTB",name:"1.5 hr — 3×5 min race-intensity, otherwise easy",detail:"Keep the engine awake. Avoid crash risk on technical terrain this week."}]}]},
    {day:"Wed",slots:[{qual:"",workouts:[{id:"w15-3",type:"run",label:"Shakeout",name:"30 min easy + 4 strides",detail:"Legs should feel fresh. Good sign."}]}]},
    {day:"Thu",slots:[{qual:"",workouts:[{id:"w15-4",type:"travel",label:"Travel",name:"Drive to Tahoe City",detail:"Arrive 2 days early. Two nights at 6,200 ft before race morning. Hydrate extra.",anchor:true}]}]},
    {day:"Fri",slots:[{qual:"",workouts:[{id:"w15-5",type:"ows",label:"Lake Swim",name:"Easy 20 min in Lake Tahoe + check-in",detail:"Cold water acclimation (low 60s°F). Wetsuit on. Packet pickup 5–7pm Commons Beach."}]},{qual:"Eve",workouts:[{id:"w15-6",type:"rest",label:"Rest",name:"Carb-load dinner, sleep 9+ hours",rest:true}]}]},
    {day:"Sat",slots:[{qual:"",workouts:[{id:"w15-7",type:"race",label:"Race",name:"🏊 1500m · 🚵 22mi MTB · 🏃 5mi Trail Run",detail:"Swim: exhale slow into the cold, find rhythm fast. Bike: conservative on first climbs. Run: altitude bites; shorter strides. Finish: Commons Beach. Go get it.",raceCard:"race-card"}]}]},
    {day:"Sun",slots:[{qual:"",workouts:[{id:"w15-8",type:"rest",label:"Celebrate",name:"BBQ at Commons Beach · Awards 12:30 PM",detail:"You just did Broken Arrow 23K and Tahoe ORT in the same month. Serious summer.",rest:true}]}]},
   ]},
 ]},
];
